name: test

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 */8 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g pnpm && pnpm i
        name: Install dependencies
      - run: pnpm build --filter esbuild-plugin-css-module-example
        name: build example app to run tests
      - name: Run unit tests
        run: pnpm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./packages/esbuild-plugin-css-module
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: esbuild-plugin-css-module
      - run: git stash --include-untracked
      - run: npx @turbo/codemod update . && pnpm update --latest -r
        name: Update dependencies
      - run: pnpm build
        name: Build all apps to make sure it is not broken due to dependency upgrades
      - name: Run unit tests
        run: pnpm test
      - name: Setup Git
        run: |
          git config --global user.name "mayank1513"
          git config --global user.email "mayank.srmu@gmail.com"
          git fetch
          git checkout main
      - name: Save upgraded packages back to repo
        run: git add . && git commit -m "upgrade deps" && git push origin main
        continue-on-error: true
